services: 
  mysql: 
    image: mysql:8
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - primeira-network

  api-docker:
    container_name: api-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - primeira-network

networks:
  primeira-network:
    name: primeira-network
    external: true
    driver: bridge

volumes:
  db: